# Site Settings
title: Behind Closed Doors
email: closed_door_dom@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  The life and thoughts of a DD/lg Dom and web programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: closed_door_dom
github_username:  closed-door-dom

# Build settings
markdown: kramdown
theme: minima
